export const CRYPTOMONEDAS = [
  { label: 'bitcoin', value: 'btcusdt' },
  { label: 'ethereum', value: 'ethusdt' },
  { label: 'bnb', value: 'bnbusdt' },
  { label: 'solana', value: 'solusdt' },
  { label: 'xrp', value: 'xrpusdt' },
  { label: 'usdc', value: 'usdcusdt' },
  { label: 'cardano', value: 'adausdt' },
  { label: 'avalanche', value: 'avaxusdt' },
  { label: 'dogecoin', value: 'dogeusdt' },
  { label: 'tron', value: 'trxusdt' },
  { label: 'polkadot', value: 'dotusdt' },
  { label: 'chainlink', value: 'linkusdt' },
  { label: 'polygon', value: 'maticusdt' },
];
